DELIMITER //
DROP PROCEDURE IF EXISTS loginUser //

CREATE PROCEDURE loginUser(
    USERNAMEE VARCHAR(20),
    PWD VARCHAR(20)
)

BEGIN
    SELECT * FROM user WHERE userName = USERNAMEE AND userPwd = PWD;
END //
DELIMITER ;